spring:
  datasource:
    username: root
<<<<<<< HEAD
    password: password
    url: "jdbc:mysql://server.natappfree.cc:34990/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
=======
    url: "jdbc:mysql://localhost:3306/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
>>>>>>> 96ef772c7243e5dd89286e37727bfff73a334b54
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123

#整合mybatis
mybatis:
  type-aliases-package: lexian.entity
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#乱码
server:
  port: 8080
  servlet:
    #context-path: /ocp
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
