spring:
  datasource:
    username: root
<<<<<<< HEAD
    password: 123
    url: "jdbc:mysql://localhost:3306/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
=======
    #password: Xy990919
    #url: "jdbc:mysql://localhost:3306/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
    #password: 123
    #url: "jdbc:mysql://localhost:3306/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
    password: password
    url: "jdbc:mysql://server.natappfree.cc:37903/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
    #password: Xy990919
    #url: "jdbc:mysql://localhost:3306/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
>>>>>>> 01729adcad0723208a59d29dccc68edde3f776aa
    driver-class-name: com.mysql.cj.jdbc.Driver

#整合mybatis
mybatis:
  type-aliases-package: lexian.entity
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#乱码
server:
  port: 8088
  servlet:
    #context-path: /ocp
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
