spring:
  datasource:
    username: root
<<<<<<< HEAD
    password: Xy990919
=======
    password: 123
>>>>>>> 310b61382626a262919887a9d9679610985d606d
    url: "jdbc:mysql://localhost:3306/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver

#整合mybatis
mybatis:
  type-aliases-package: lexian.entity
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#乱码
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
