spring:
  datasource:
    username: root
<<<<<<< HEAD
    password: password
    url: "jdbc:mysql://server.natappfree.cc:46813/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
=======
<<<<<<< HEAD
    password: password
    url: "jdbc:mysql://server.natappfree.cc:40697/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
>>>>>>> c8a72d19cc8ce11718aa483687c4c56ab041c40b

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接只读数据库时配置为true， 保证安全
      read-only: false
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 450000
      # 连接池中允许的最大连接数。缺省值：10
      maximum-pool-size: 60
      minimum-idle: 10
<<<<<<< HEAD
=======
=======
    password: 123456
    url: "jdbc:mysql://localhost:3306/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
>>>>>>> 7cc8a3ed0c589d58079118b055ceedc47447ab83
>>>>>>> c8a72d19cc8ce11718aa483687c4c56ab041c40b

#整合mybatis
mybatis:
  type-aliases-package: lexian.entity
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#乱码
server:
  port: 8080
  servlet:
    #context-path: /ocp
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
<<<<<<< HEAD


=======
<<<<<<< HEAD


=======
>>>>>>> 7cc8a3ed0c589d58079118b055ceedc47447ab83
>>>>>>> c8a72d19cc8ce11718aa483687c4c56ab041c40b
