spring:
  datasource:
    username: root
    password: password
    url: "jdbc:mysql://server.natappfree.cc:42916/lexian?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 连接只读数据库时配置为true， 保证安全
      read-only: false
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 600000
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 450000
      # 连接池中允许的最大连接数。缺省值：10
      maximum-pool-size: 60
      minimum-idle: 10

  redis:
    database:
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-active: 100
          max-idle: 10
          max-wait: 100000
      timeout: 5000

#整合mybatis
mybatis:
  type-aliases-package: lexian.entity
  mapper-locations: classpath:mybatis/mappers/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#乱码
server:
  port: 8088
  servlet:
    #context-path: /ocp
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#pagehelper分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql





